{{- if and .Values.proxy.enabled (not .Values.standalone.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus-ha.proxy.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "proxy"
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: "proxy"
  template:
    metadata:
      labels:
{{ include "milvus-ha.matchLabels" . | indent 8 }}
        component: "proxy"
    spec:
      {{- if .Values.image.all.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.all.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: proxy
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: {{ .Values.image.all.pullPolicy }}
        args: [ "/milvus/bin/milvus", "run", "proxynode" ]
        env:
          - name: ETCD_ENDPOINTS
            value: "{{ template "milvus-ha.etcd.endpoints" . }}"
          - name: PULSAR_ADDRESS
            value: "pulsar://{{ template "milvus-ha.pulsar.address" . }}"
          - name: MASTER_ADDRESS
            value: "{{ template "milvus-ha.rootcoord.fullname" . }}:{{ .Values.rootCoordinator.service.port }}"
          - name: DATA_SERVICE_ADDRESS
            value: "{{ template "milvus-ha.datacoord.fullname" . }}:{{ .Values.dataCoordinator.service.port }}"
          - name: INDEX_SERVICE_ADDRESS
            value: "{{ template "milvus-ha.indexcoord.fullname" . }}:{{ .Values.indexCoordinator.service.port }}"
          - name: QUERY_SERVICE_ADDRESS
            value: "{{ template "milvus-ha.querycoord.fullname" . }}:{{ .Values.queryCoordinator.service.port }}"
        {{- if .Values.proxy.extraEnv }}
          {{- toYaml .Values.proxy.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: proxy
            containerPort: 19530
            protocol: TCP
          {{- if .Values.metrics.enabled }}
          - name: metrics
            containerPort: 9091
            protocol: TCP
          {{- end }}
        resources:
          {{- toYaml .Values.proxy.resources | nindent 10 }}
        volumeMounts:
        - name: milvus-ha-config
          mountPath: /milvus/configs/milvus.yaml
          subPath: milvus.yaml
          readOnly: true
        - name: milvus-logs-disk
          mountPath: {{ .Values.logsPersistence.mountPath | quote }}
          subPath: {{ .Values.logsPersistence.persistentVolumeClaim.subPath | default "" }}

      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: milvus-ha-config
        configMap:
          name: {{ template "milvus-ha.fullname" . }}
      - name: milvus-logs-disk
        {{- if .Values.logsPersistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.logsPersistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "milvus-ha.fullname" . | trunc 58)) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
