{{- if and (not .Values.pulsar.enabled) .Values.cluster.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus.pulsar.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "pulsar"
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: "pulsar"
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "pulsar"
    spec:
      {{- if .Values.pulsarStandalone.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.pulsarStandalone.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: pulsar
        image: "{{ .Values.pulsarStandalone.image.repository }}:{{ .Values.pulsarStandalone.image.tag }}"
        imagePullPolicy: {{ .Values.pulsarStandalone.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
          - pulsar_conf_path=/pulsar/conf/standalone.conf;
            echo "" >> $pulsar_conf_path;
            echo "maxMessageSize=1073741824" >> $pulsar_conf_path;
            echo "" >> $pulsar_conf_path;
            echo "nettyMaxFrameSizeBytes=1073741824" >> $pulsar_conf_path;
            bin/pulsar standalone;

        {{- if .Values.pulsarStandalone.extraEnv }}
        env:
          {{- toYaml .Values.pulsarStandalone.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: pulsar
            containerPort: 6650
            protocol: TCP
        resources:
          {{- toYaml .Values.pulsarStandalone.resources | nindent 10 }}

      {{- with .Values.pulsarStandalone.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pulsarStandalone.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pulsarStandalone.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}